import type { RepositoryAnalysis } from '@repo-archaeologist/core';

/** Pre-built demo analysis showcasing Repo Archaeologist capabilities */
export const demoAnalysis: RepositoryAnalysis = {
  id: 'demo-agent-runtime',
  url: 'https://github.com/example/agent-runtime',
  name: 'agent-runtime',
  owner: 'example',
  analyzedAt: new Date().toISOString(),
  defaultBranch: 'main',
  totalCommits: 847,
  snapshots: [
    {
      id: 'snap-a1b2c3d',
      commit: 'a1b2c3d4e5f6789012345678901234567890abcd',
      shortCommit: 'a1b2c3d',
      timestamp: '2023-01-15T10:00:00Z',
      message: 'Initial commit: CLI + LLM wrapper',
      author: 'Alice',
      totalFiles: 12,
      totalLines: 890,
      modules: [
        { id: 'src-cli', name: 'cli', path: 'src/cli', fileCount: 3, linesOfCode: 210, symbols: ['main', 'parseArgs', 'runCLI'] },
        { id: 'src-core', name: 'core', path: 'src/core', fileCount: 5, linesOfCode: 480, symbols: ['LLMClient', 'Prompt', 'Response'] },
      ],
      dependencies: [{ from: 'src-cli', to: 'src-core', weight: 2 }],
    },
    {
      id: 'snap-b2c3d4e',
      commit: 'b2c3d4e5f6789012345678901234567890abcde',
      shortCommit: 'b2c3d4e',
      timestamp: '2023-08-22T14:30:00Z',
      message: 'Add storage layer and config module',
      author: 'Bob',
      totalFiles: 28,
      totalLines: 2340,
      modules: [
        { id: 'src-cli', name: 'cli', path: 'src/cli', fileCount: 4, linesOfCode: 280, symbols: ['main', 'parseArgs', 'runCLI', 'ConfigLoader'] },
        { id: 'src-core', name: 'core', path: 'src/core', fileCount: 6, linesOfCode: 520, symbols: ['LLMClient', 'Prompt', 'Response', 'Agent'] },
        { id: 'src-storage', name: 'storage', path: 'src/storage', fileCount: 5, linesOfCode: 680, symbols: ['Storage', 'FileStore', 'Cache'] },
        { id: 'src-config', name: 'config', path: 'src/config', fileCount: 3, linesOfCode: 340, symbols: ['Config', 'loadConfig', 'validateConfig'] },
      ],
      dependencies: [
        { from: 'src-cli', to: 'src-core', weight: 2 },
        { from: 'src-cli', to: 'src-config', weight: 1 },
        { from: 'src-core', to: 'src-storage', weight: 3 },
        { from: 'src-config', to: 'src-storage', weight: 1 },
      ],
    },
    {
      id: 'snap-c3d4e5f',
      commit: 'c3d4e5f6789012345678901234567890abcdef',
      shortCommit: 'c3d4e5f',
      timestamp: '2024-03-10T09:15:00Z',
      message: 'Introduce Agent abstraction with tools support',
      author: 'Alice',
      totalFiles: 45,
      totalLines: 4120,
      modules: [
        { id: 'src-cli', name: 'cli', path: 'src/cli', fileCount: 5, linesOfCode: 320, symbols: ['main', 'runCLI'] },
        { id: 'src-agent', name: 'agent', path: 'src/agent', fileCount: 8, linesOfCode: 1240, symbols: ['Agent', 'Agent.run', 'AgentContext', 'Planner'] },
        { id: 'src-tools', name: 'tools', path: 'src/tools', fileCount: 6, linesOfCode: 890, symbols: ['ToolRegistry', 'Tool', 'ToolAdapter'] },
        { id: 'src-storage', name: 'storage', path: 'src/storage', fileCount: 5, linesOfCode: 680, symbols: ['Storage', 'FileStore'] },
        { id: 'src-config', name: 'config', path: 'src/config', fileCount: 3, linesOfCode: 340, symbols: ['Config'] },
      ],
      dependencies: [
        { from: 'src-cli', to: 'src-agent', weight: 2 },
        { from: 'src-agent', to: 'src-tools', weight: 4 },
        { from: 'src-agent', to: 'src-storage', weight: 2 },
        { from: 'src-tools', to: 'src-config', weight: 1 },
      ],
    },
    {
      id: 'snap-d4e5f6a',
      commit: 'd4e5f6789012345678901234567890abcdef0',
      shortCommit: 'd4e5f6a',
      timestamp: '2024-08-17T16:45:00Z',
      message: 'Split Agent into Planner + Executor',
      author: 'Carol',
      totalFiles: 62,
      totalLines: 5680,
      modules: [
        { id: 'src-cli', name: 'cli', path: 'src/cli', fileCount: 5, linesOfCode: 340, symbols: ['main', 'runCLI'] },
        { id: 'src-runtime', name: 'runtime', path: 'src/runtime', fileCount: 4, linesOfCode: 560, symbols: ['Runtime', 'Runtime.execute'] },
        { id: 'src-agent', name: 'agent', path: 'src/agent', fileCount: 3, linesOfCode: 420, symbols: ['AgentContext'] },
        { id: 'src-planner', name: 'planner', path: 'src/planner', fileCount: 5, linesOfCode: 780, symbols: ['Planner', 'Plan', 'PlanStep'] },
        { id: 'src-executor', name: 'executor', path: 'src/executor', fileCount: 4, linesOfCode: 650, symbols: ['Executor', 'ExecutionResult'] },
        { id: 'src-tools', name: 'tools', path: 'src/tools', fileCount: 7, linesOfCode: 920, symbols: ['ToolRegistry', 'Tool'] },
        { id: 'src-storage', name: 'storage', path: 'src/storage', fileCount: 5, linesOfCode: 680, symbols: ['Storage'] },
      ],
      dependencies: [
        { from: 'src-cli', to: 'src-runtime', weight: 2 },
        { from: 'src-runtime', to: 'src-planner', weight: 3 },
        { from: 'src-runtime', to: 'src-executor', weight: 3 },
        { from: 'src-runtime', to: 'src-tools', weight: 2 },
        { from: 'src-planner', to: 'src-agent', weight: 1 },
        { from: 'src-executor', to: 'src-tools', weight: 4 },
      ],
    },
    {
      id: 'snap-e5f6a7b',
      commit: 'e5f6a7b89012345678901234567890abcdef01',
      shortCommit: 'e5f6a7b',
      timestamp: '2025-01-20T11:00:00Z',
      message: 'Add MCP support and Memory module',
      author: 'Dave',
      totalFiles: 89,
      totalLines: 7840,
      modules: [
        { id: 'src-cli', name: 'cli', path: 'src/cli', fileCount: 5, linesOfCode: 360, symbols: ['main'] },
        { id: 'src-runtime', name: 'runtime', path: 'src/runtime', fileCount: 6, linesOfCode: 890, symbols: ['Runtime', 'Runtime.execute'] },
        { id: 'src-planner', name: 'planner', path: 'src/planner', fileCount: 5, linesOfCode: 780, symbols: ['Planner'] },
        { id: 'src-executor', name: 'executor', path: 'src/executor', fileCount: 4, linesOfCode: 650, symbols: ['Executor'] },
        { id: 'src-tools', name: 'tools', path: 'src/tools', fileCount: 4, linesOfCode: 480, symbols: ['ToolRegistry'] },
        { id: 'src-mcp', name: 'mcp', path: 'src/mcp', fileCount: 6, linesOfCode: 920, symbols: ['MCPClient', 'MCPRegistry', 'MCPTool'] },
        { id: 'src-memory', name: 'memory', path: 'src/memory', fileCount: 7, linesOfCode: 1100, symbols: ['Memory', 'WorkingMemory', 'LongTermMemory', 'VectorStore'] },
        { id: 'src-storage', name: 'storage', path: 'src/storage', fileCount: 5, linesOfCode: 680, symbols: ['Storage'] },
      ],
      dependencies: [
        { from: 'src-cli', to: 'src-runtime', weight: 2 },
        { from: 'src-runtime', to: 'src-planner', weight: 2 },
        { from: 'src-runtime', to: 'src-executor', weight: 2 },
        { from: 'src-runtime', to: 'src-memory', weight: 3 },
        { from: 'src-executor', to: 'src-mcp', weight: 5 },
        { from: 'src-memory', to: 'src-storage', weight: 2 },
        { from: 'src-mcp', to: 'src-tools', weight: 1 },
      ],
    },
  ],
  deltas: [
    {
      fromSnapshotId: 'snap-a1b2c3d',
      toSnapshotId: 'snap-b2c3d4e',
      added: [
        { id: 'src-storage', name: 'storage', path: 'src/storage', fileCount: 5, linesOfCode: 680, symbols: ['Storage'] },
        { id: 'src-config', name: 'config', path: 'src/config', fileCount: 3, linesOfCode: 340, symbols: ['Config'] },
      ],
      removed: [],
      moved: [],
      dependencyChanges: { added: [{ from: 'src-core', to: 'src-storage', weight: 3 }], removed: [] },
      changes: [
        { type: 'added', module: 'storage', detail: 'New module at src/storage' },
        { type: 'added', module: 'config', detail: 'New module at src/config' },
      ],
    },
    {
      fromSnapshotId: 'snap-b2c3d4e',
      toSnapshotId: 'snap-c3d4e5f',
      added: [
        { id: 'src-agent', name: 'agent', path: 'src/agent', fileCount: 8, linesOfCode: 1240, symbols: ['Agent'] },
        { id: 'src-tools', name: 'tools', path: 'src/tools', fileCount: 6, linesOfCode: 890, symbols: ['ToolRegistry'] },
      ],
      removed: [
        { id: 'src-core', name: 'core', path: 'src/core', fileCount: 6, linesOfCode: 520, symbols: ['LLMClient'] },
      ],
      moved: [],
      dependencyChanges: { added: [{ from: 'src-agent', to: 'src-tools', weight: 4 }], removed: [{ from: 'src-cli', to: 'src-core', weight: 2 }] },
      changes: [
        { type: 'added', module: 'agent', detail: 'New module at src/agent' },
        { type: 'added', module: 'tools', detail: 'New module at src/tools' },
        { type: 'removed', module: 'core', detail: 'Module removed from src/core' },
      ],
    },
    {
      fromSnapshotId: 'snap-c3d4e5f',
      toSnapshotId: 'snap-d4e5f6a',
      added: [
        { id: 'src-runtime', name: 'runtime', path: 'src/runtime', fileCount: 4, linesOfCode: 560, symbols: ['Runtime'] },
        { id: 'src-planner', name: 'planner', path: 'src/planner', fileCount: 5, linesOfCode: 780, symbols: ['Planner'] },
        { id: 'src-executor', name: 'executor', path: 'src/executor', fileCount: 4, linesOfCode: 650, symbols: ['Executor'] },
      ],
      removed: [],
      moved: [],
      dependencyChanges: { added: [{ from: 'src-runtime', to: 'src-planner', weight: 3 }], removed: [] },
      changes: [
        { type: 'added', module: 'runtime', detail: 'New orchestration layer' },
        { type: 'split', module: 'agent', to: ['planner', 'executor'], detail: 'Agent split into Planner + Executor' },
      ],
    },
    {
      fromSnapshotId: 'snap-d4e5f6a',
      toSnapshotId: 'snap-e5f6a7b',
      added: [
        { id: 'src-mcp', name: 'mcp', path: 'src/mcp', fileCount: 6, linesOfCode: 920, symbols: ['MCPClient'] },
        { id: 'src-memory', name: 'memory', path: 'src/memory', fileCount: 7, linesOfCode: 1100, symbols: ['Memory'] },
      ],
      removed: [],
      moved: [],
      dependencyChanges: { added: [{ from: 'src-executor', to: 'src-mcp', weight: 5 }], removed: [] },
      changes: [
        { type: 'added', module: 'mcp', detail: 'MCP protocol support' },
        { type: 'added', module: 'memory', detail: 'Memory subsystem with WorkingMemory + LongTermMemory' },
        { type: 'moved', module: 'tools', from: 'src/tools', to: ['src/mcp'], detail: 'Tool protocol migrated to MCP' },
      ],
    },
  ],
  evolutionEvents: [
    {
      id: 'event-1',
      type: 'feature_introduction',
      title: 'Introduce storage, config',
      summary: 'New modules were introduced: storage, config. The project gained persistent storage and configuration management capabilities across 4 commits.',
      period: { start: '2023-08-01T00:00:00Z', end: '2023-08-22T14:30:00Z' },
      startCommit: 'b2c3d4e5f6789012345678901234567890abcde',
      endCommit: 'b2c3d4e5f6789012345678901234567890abcde',
      commits: ['b2c3d4e5f6789012345678901234567890abcde'],
      affectedModules: ['storage', 'config'],
      changes: [
        { type: 'added', module: 'storage', detail: 'New module at src/storage' },
        { type: 'added', module: 'config', detail: 'New module at src/config' },
      ],
      evidence: [
        { kind: 'commit_message', description: 'Add storage layer and config module', ref: 'b2c3d4e' },
        { kind: 'module_delta', description: 'New module at src/storage' },
        { kind: 'file_change', description: '16 files changed across 4 commits' },
      ],
      blastRadius: { filesChanged: 16, modulesAffected: 2, dependenciesChanged: 3, heatmap: { src: 2 } },
    },
    {
      id: 'event-2',
      type: 'architecture_migration',
      title: 'Architecture migration: retire core, add agent',
      summary: 'The project underwent an architectural migration affecting 3 modules. The simple LLM wrapper evolved into a full Agent abstraction with tools support.',
      period: { start: '2024-02-01T00:00:00Z', end: '2024-03-10T09:15:00Z' },
      startCommit: 'c3d4e5f6789012345678901234567890abcdef',
      endCommit: 'c3d4e5f6789012345678901234567890abcdef',
      commits: ['c3d4e5f6789012345678901234567890abcdef'],
      affectedModules: ['agent', 'tools', 'core'],
      changes: [
        { type: 'added', module: 'agent', detail: 'New module at src/agent' },
        { type: 'added', module: 'tools', detail: 'New module at src/tools' },
        { type: 'removed', module: 'core', detail: 'Module removed from src/core' },
      ],
      evidence: [
        { kind: 'commit_message', description: 'Introduce Agent abstraction with tools support', ref: 'c3d4e5f' },
        { kind: 'module_delta', description: 'removed: core' },
        { kind: 'dependency_change', description: '4 dependency relationship changes detected' },
      ],
      blastRadius: { filesChanged: 32, modulesAffected: 3, dependenciesChanged: 4, heatmap: { src: 3 } },
    },
    {
      id: 'event-3',
      type: 'module_split',
      title: 'Agent split into Planner + Executor',
      summary: 'A module was split into separate components across 11 commits. The monolithic Agent class was decomposed into Planner and Executor with a new Runtime orchestration layer.',
      period: { start: '2024-07-01T00:00:00Z', end: '2024-08-17T16:45:00Z' },
      startCommit: 'd4e5f6789012345678901234567890abcdef0',
      endCommit: 'd4e5f6789012345678901234567890abcdef0',
      commits: ['d4e5f6789012345678901234567890abcdef0'],
      affectedModules: ['agent', 'runtime', 'planner', 'executor'],
      changes: [
        { type: 'added', module: 'runtime', detail: 'New orchestration layer' },
        { type: 'split', module: 'agent', to: ['planner', 'executor'], detail: 'Agent split into Planner + Executor' },
      ],
      evidence: [
        { kind: 'commit_message', description: 'Split Agent into Planner + Executor', ref: 'd4e5f6a' },
        { kind: 'module_delta', description: 'Agent split into Planner + Executor' },
        { kind: 'file_change', description: '38 files changed across 11 commits' },
      ],
      blastRadius: { filesChanged: 38, modulesAffected: 4, dependenciesChanged: 6, heatmap: { src: 4 } },
    },
    {
      id: 'event-4',
      type: 'architecture_migration',
      title: 'Architecture migration, add mcp',
      summary: 'The project underwent an architectural migration affecting 2 modules. Custom tool adapters were replaced with MCP protocol support, and a Memory subsystem was introduced.',
      period: { start: '2025-01-01T00:00:00Z', end: '2025-01-20T11:00:00Z' },
      startCommit: 'e5f6a7b89012345678901234567890abcdef01',
      endCommit: 'e5f6a7b89012345678901234567890abcdef01',
      commits: ['e5f6a7b89012345678901234567890abcdef01'],
      affectedModules: ['mcp', 'memory', 'tools'],
      changes: [
        { type: 'added', module: 'mcp', detail: 'MCP protocol support' },
        { type: 'added', module: 'memory', detail: 'Memory subsystem' },
        { type: 'moved', module: 'tools', from: 'src/tools', to: ['src/mcp'], detail: 'Tool protocol migrated to MCP' },
      ],
      evidence: [
        { kind: 'commit_message', description: 'Add MCP support and Memory module', ref: 'e5f6a7b' },
        { kind: 'module_delta', description: 'Tool protocol migrated to MCP' },
        { kind: 'dependency_change', description: '5 dependency relationship changes detected' },
      ],
      blastRadius: { filesChanged: 27, modulesAffected: 3, dependenciesChanged: 5, heatmap: { src: 3 } },
    },
  ],
  moduleEvolutions: [
    {
      module: 'runtime',
      bornAt: '2024-08-17T16:45:00Z',
      bornCommit: 'd4e5f6a',
      events: [
        { kind: 'born', timestamp: '2024-08-17T16:45:00Z', commit: 'd4e5f6a', detail: 'First seen at src/runtime' },
      ],
      currentDependencies: ['planner', 'executor', 'memory'],
    },
    {
      module: 'memory',
      bornAt: '2025-01-20T11:00:00Z',
      bornCommit: 'e5f6a7b',
      events: [
        { kind: 'born', timestamp: '2025-01-20T11:00:00Z', commit: 'e5f6a7b', detail: 'First seen at src/memory' },
      ],
      currentDependencies: ['storage'],
    },
    {
      module: 'mcp',
      bornAt: '2025-01-20T11:00:00Z',
      bornCommit: 'e5f6a7b',
      events: [
        { kind: 'born', timestamp: '2025-01-20T11:00:00Z', commit: 'e5f6a7b', detail: 'First seen at src/mcp' },
      ],
      currentDependencies: ['tools'],
    },
  ],
  timeline: [
    { timestamp: '2023-01-15T10:00:00Z', commit: 'a1b2c3d4e5f6789012345678901234567890abcd', shortCommit: 'a1b2c3d', label: '2023.01', snapshotId: 'snap-a1b2c3d', eventIds: [] },
    { timestamp: '2023-08-22T14:30:00Z', commit: 'b2c3d4e5f6789012345678901234567890abcde', shortCommit: 'b2c3d4e', label: '2023.08', snapshotId: 'snap-b2c3d4e', eventIds: ['event-1'] },
    { timestamp: '2024-03-10T09:15:00Z', commit: 'c3d4e5f6789012345678901234567890abcdef', shortCommit: 'c3d4e5f', label: '2024.03', snapshotId: 'snap-c3d4e5f', eventIds: ['event-2'] },
    { timestamp: '2024-08-17T16:45:00Z', commit: 'd4e5f6789012345678901234567890abcdef0', shortCommit: 'd4e5f6a', label: '2024.08', snapshotId: 'snap-d4e5f6a', eventIds: ['event-3'] },
    { timestamp: '2025-01-20T11:00:00Z', commit: 'e5f6a7b89012345678901234567890abcdef01', shortCommit: 'e5f6a7b', label: '2025.01', snapshotId: 'snap-e5f6a7b', eventIds: ['event-4'] },
  ],
};
